# Generated by Django 4.1 on 2022-08-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0002_alter_palavras_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Palavras',
            new_name='Palavra',
        ),
    ]
